---
- name: Install and Configure NGINX Server
  hosts: all
  become: yes 
  gather facts: yes 
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes 

    - name: Install NGINX Server
      apt:
        name: nginx
        state: present
  
    - name: Start and Enable NGINX Server
      service:
        name: nginx
        state: started
        enabled: yes 
  
    - name: Deploy static website  
      copy:
        src: index.html  
        dest: /var/www/html/      
